baseURL: "/"
title: Ricardo Ancona
paginate: 20
theme: hugo-PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
# googleAnalytics: UA-123-45

minify:
    disableXML: true
    # minifyOutput: true

languages:
    en:
        languageName: "English"
        weight: 1
        menu:
            main:
                - name: About
                  url: about
                  weight: 5
                - name: Archive
                  url: archives
                  weight: 5
                # - name: Projects
                #   url: projects/
                #   weight: 10
                - name: Search
                  url: search/
                  weight: 10
                - name: Tags
                  url: tags/
                  weight: 10

    es:
        languageName: ":cactus:"
        languageAltTitle: Español
        weight: 2
        title: Ricardo Ancona
        profileMode:
            enabled: true
            title: Hola
            # imageUrl: /static/cairo_logo.jpeg
            # imageTitle: my image
            # imageWidth: 120
            # imageHeight: 120
            subtitle: "
            Soy Ricardo.
            <br />
            Tuve un cine en Mérida, México por 10 años ([**Cairo Cinema Café**](https://www.ricardoancona.com/posts/cairo-cinema/)).
            <br />
            Ahora vivo en Berlin.
            <br /><br />
            (Casi todo está en inglés por aquí por ahora.)
            <br />

            <br />
            "
          #  buttons:
          #      - name: Blog
          #        url: posts
          #      - name: Tags
          #        url: tags
        # menu:
        #    main:
        #        - name: About
        #          url: about/
        #          weight: 5
        #        - name: Archive
        #          url: archives/
        #          weight: 5
        #        - name: Projects
        #          url: projects/
        #        weight: 10
        #      - name: Search
        #        url: search/
        #        weight: 10
        #      - name: Tags
        #        url: tags/
        #        weight: 10




outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "Theme PaperMod - https://github.com/adityatelange/hugo-PaperMod"
    author: Ricardo
    # author: ["Me", "You"] # multiple authors

    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: true
    # disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true
    # comments: false
    images: ["papermod-cover.png"]

    profileMode:
        enabled: false
        title: PaperMod
        imageUrl: /static/cairo_logo.jpeg
        imageTitle: my image
        # imageWidth: 120
        # imageHeight: 120
        buttons:
            - name: Archives
              url: archives
            - name: Tags
              url: tags

    homeInfoParams:
        Title: "Hola"
        Content: >
            - * I'm Ricardo.

            - *

            - * I ran an independent cinema ([**Cairo Cinema Café**](https://www.ricardoancona.com/posts/cairo-cinema/)) in México for almost 10 years.

            - * Now I live in Berlin.

            - *

            - * More [**here**](https://www.ricardoancona.com/about/).




    socialIcons:
        - name: twitter
          url: "https://twitter.com/WittyGuacamole"
        - name: linkedin
          url: "https://www.linkedin.com/in/ricardoancona/"
        - name: email
          url: "mailto:ricardoancona@gmail.com"
        - name: RsS
          url: "index.xml"


    editPost:
        URL: "https://github.com/adityatelange/hugo-PaperMod/tree/exampleSite/content"
        Text: "Suggest Changes" # edit text
        appendFilePath: true # to append file path to Edit link

    # label:
    #     text: "Home"
    #     icon: icon.png
    #     iconHeight: 35

    # analytics:
    #     google:
    #         SiteVerificationTag: "XYZabc"

    assets:
         favicon: "/favicon.ico"
    #     favicon16x16: "<link / abs url>"
    #     favicon32x32: "<link / abs url>"
    #     apple_touch_icon: "<link / abs url>"
    #     safari_pinned_tab: "<link / abs url>"

    # cover:
    #     hidden: true # hide everywhere but not in structured data
    #     hiddenInList: true # hide on list pages and home
    #     hiddenInSingle: true # hide on single page

    # fuseOpts:
    #     isCaseSensitive: false
    #     shouldSort: true
    #     location: 0
    #     distance: 1000
    #     threshold: 0.4
    #     minMatchCharLength: 0
    #     keys: ["title", "permalink", "summary", "content"]

taxonomies:
    category: categories
    tag: tags
    series: series

markup:
    goldmark:
        renderer:
            unsafe: true
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         # noClasses: false
#         style: monokai

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true
